package com.example.bidoo_backend.enums;

public enum NotificationType {
    AUCTION_CREATED,
    AUCTION_CLOSED,
    BID_PLACED,
    BID_OUTBID,
    AUCTION_ENDING_SOON,
    YOU_WON_AUCTION,
    PAYMENT_REQUIRED,
    PAYMENT_RECEIVED,
    AUCTION_CANCELLED,
    SUSPICIOUS_ACTIVITY,
    SYSTEM_ANNOUNCEMENT,
    AUCTION_APPROVED,
    AUCTION_REJECTED,
    AUCTION_MODERATED
}
